openapi: 3.0.0
info:
  title: Travel Advisor API
  version: 1.0.0

paths:

  /search:
    get:
      summary: Search places
      parameters:
        - in: query
          name: q
          schema:
            type: string
      responses:
        200:
          description: List places

  /itinerary:
    post:
      summary: Create itinerary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                creator_id:
                  type: string
                description:
                  type: string

  /explore:
    get:
      summary: Get explore screen data
      responses:
        200:
          description: Explore data

  /places:
    get:
      summary: Get places
      responses:
        200:
          description: List of places

  /places/{id}:
    get:
      summary: Get place detail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Place detail

  /reviews:
    post:
      summary: Create review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                place_id:
                  type: string
                rating:
                  type: integer
                comment:
                  type: string
      responses:
        201:
          description: Review created