-- Tripvivu web survey data is intentionally isolated from application data.
-- Browser clients never access these tables directly; the Vercel function uses
-- service-role-only RPCs declared at the bottom of this migration.

CREATE SCHEMA IF NOT EXISTS survey;

REVOKE ALL ON SCHEMA survey FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA survey TO service_role;

CREATE TABLE IF NOT EXISTS survey.participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  age_group text NOT NULL,
  travel_frequency text NOT NULL,
  travel_style text NOT NULL,
  planning_frequency text NOT NULL,
  status text NOT NULL DEFAULT 'STARTED'
    CHECK (status IN ('STARTED', 'ITINERARY_CREATED', 'COMPLETED')),
  current_itinerary_id uuid REFERENCES travel.itineraries(id) ON DELETE SET NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT survey_participants_email_lowercase CHECK (email = lower(email)),
  CONSTRAINT survey_participants_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS survey.responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  participant_id uuid NOT NULL UNIQUE REFERENCES survey.participants(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  itinerary_id uuid NOT NULL REFERENCES travel.itineraries(id) ON DELETE CASCADE,
  survey_version integer NOT NULL DEFAULT 1,
  recommendation_ratings jsonb NOT NULL,
  itinerary_quality_ratings jsonb NOT NULL,
  customization_ratings jsonb NOT NULL,
  system_value_ratings jsonb NOT NULL,
  difficulties text NOT NULL,
  improvement_priority text NOT NULL,
  feature_suggestions text NOT NULL,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT survey_recommendation_ratings_object CHECK (jsonb_typeof(recommendation_ratings) = 'object'),
  CONSTRAINT survey_itinerary_quality_ratings_object CHECK (jsonb_typeof(itinerary_quality_ratings) = 'object'),
  CONSTRAINT survey_customization_ratings_object CHECK (jsonb_typeof(customization_ratings) = 'object'),
  CONSTRAINT survey_system_value_ratings_object CHECK (jsonb_typeof(system_value_ratings) = 'object')
);

CREATE TABLE IF NOT EXISTS survey.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_id uuid NOT NULL REFERENCES survey.participants(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  itinerary_id uuid REFERENCES travel.itineraries(id) ON DELETE CASCADE,
  event_type text NOT NULL
    CHECK (event_type IN ('ITINERARY_CREATED', 'SURVEY_OPENED', 'SURVEY_SUBMITTED')),
  event_key text GENERATED ALWAYS AS (
    event_type || ':' || COALESCE(itinerary_id::text, 'NONE')
  ) STORED,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT survey_events_once UNIQUE (participant_id, event_key)
);

CREATE INDEX IF NOT EXISTS survey_participants_status_idx
  ON survey.participants (status, started_at DESC);
CREATE INDEX IF NOT EXISTS survey_responses_submitted_idx
  ON survey.responses (submitted_at DESC);
CREATE INDEX IF NOT EXISTS survey_events_type_created_idx
  ON survey.events (event_type, created_at DESC);

ALTER TABLE survey.participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey.responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey.events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON ALL TABLES IN SCHEMA survey FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA survey TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA survey TO service_role;

CREATE OR REPLACE VIEW survey.tracking_summary AS
SELECT
  COUNT(*)::bigint AS participants_started,
  COUNT(*) FILTER (WHERE p.status IN ('ITINERARY_CREATED', 'COMPLETED'))::bigint AS participants_created_itinerary,
  (
    SELECT COUNT(DISTINCT e.participant_id)::bigint
    FROM survey.events e
    WHERE e.event_type = 'SURVEY_OPENED'
  ) AS participants_opened_survey,
  COUNT(*) FILTER (WHERE p.status = 'COMPLETED')::bigint AS surveys_completed,
  COUNT(*) FILTER (WHERE p.status = 'STARTED')::bigint AS surveys_in_progress,
  CASE
    WHEN COUNT(*) = 0 THEN 0
    ELSE ROUND(
      COUNT(*) FILTER (WHERE p.status = 'COMPLETED')::numeric * 100 / COUNT(*),
      2
    )
  END AS completion_rate_percent,
  MAX(p.started_at) AS latest_started_at,
  MAX(p.completed_at) AS latest_completed_at
FROM survey.participants p;

CREATE OR REPLACE VIEW survey.daily_tracking AS
SELECT
  (p.started_at AT TIME ZONE 'Asia/Ho_Chi_Minh')::date AS survey_date,
  COUNT(*)::bigint AS participants_started,
  COUNT(*) FILTER (WHERE p.status IN ('ITINERARY_CREATED', 'COMPLETED'))::bigint AS participants_created_itinerary,
  COUNT(*) FILTER (WHERE p.status = 'COMPLETED')::bigint AS surveys_completed
FROM survey.participants p
GROUP BY (p.started_at AT TIME ZONE 'Asia/Ho_Chi_Minh')::date
ORDER BY survey_date DESC;

GRANT SELECT ON survey.tracking_summary, survey.daily_tracking TO service_role;

CREATE OR REPLACE FUNCTION public.survey_get_participant_by_email(p_email text)
RETURNS TABLE (
  participant_id uuid,
  user_id uuid,
  email text,
  status text,
  current_itinerary_id uuid
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT p.id, p.user_id, p.email, p.status, p.current_itinerary_id
  FROM survey.participants p
  WHERE p.email = lower(trim(p_email))
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.survey_upsert_participant(
  p_user_id uuid,
  p_email text,
  p_age_group text,
  p_travel_frequency text,
  p_travel_style text,
  p_planning_frequency text
)
RETURNS TABLE (
  participant_id uuid,
  user_id uuid,
  email text,
  status text,
  current_itinerary_id uuid
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO survey.participants (
    user_id,
    email,
    age_group,
    travel_frequency,
    travel_style,
    planning_frequency
  )
  VALUES (
    p_user_id,
    lower(trim(p_email)),
    p_age_group,
    p_travel_frequency,
    p_travel_style,
    p_planning_frequency
  )
  -- Dùng tên constraint thay vì ON CONFLICT (email). Hàm RETURNS TABLE có
  -- output parameter cũng tên "email", khiến PL/pgSQL báo ambiguous.
  ON CONFLICT ON CONSTRAINT survey_participants_email_unique DO UPDATE SET
    age_group = EXCLUDED.age_group,
    travel_frequency = EXCLUDED.travel_frequency,
    travel_style = EXCLUDED.travel_style,
    planning_frequency = EXCLUDED.planning_frequency,
    last_seen_at = now(),
    updated_at = now();

  RETURN QUERY
  SELECT p.id, p.user_id, p.email, p.status, p.current_itinerary_id
  FROM survey.participants p
  WHERE p.email = lower(trim(p_email))
  LIMIT 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.survey_record_event(
  p_participant_id uuid,
  p_user_id uuid,
  p_itinerary_id uuid,
  p_event_type text,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_event_type NOT IN ('ITINERARY_CREATED', 'SURVEY_OPENED', 'SURVEY_SUBMITTED') THEN
    RAISE EXCEPTION 'Unsupported survey event type';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM survey.participants p
    WHERE p.id = p_participant_id AND p.user_id = p_user_id
  ) THEN
    RAISE EXCEPTION 'Survey participant not found';
  END IF;

  IF p_itinerary_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM travel.itineraries i
    WHERE i.id = p_itinerary_id AND i.creator_id = p_user_id
  ) THEN
    RAISE EXCEPTION 'Itinerary does not belong to participant';
  END IF;

  INSERT INTO survey.events (
    participant_id, user_id, itinerary_id, event_type, metadata
  )
  VALUES (
    p_participant_id, p_user_id, p_itinerary_id, p_event_type, COALESCE(p_metadata, '{}'::jsonb)
  )
  ON CONFLICT (participant_id, event_key) DO UPDATE SET
    metadata = EXCLUDED.metadata;

  IF p_event_type = 'ITINERARY_CREATED' THEN
    UPDATE survey.participants
    SET
      status = CASE WHEN status = 'COMPLETED' THEN status ELSE 'ITINERARY_CREATED' END,
      current_itinerary_id = p_itinerary_id,
      last_seen_at = now(),
      updated_at = now()
    WHERE id = p_participant_id;
  ELSE
    UPDATE survey.participants
    SET last_seen_at = now(), updated_at = now()
    WHERE id = p_participant_id;
  END IF;

  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.survey_submit_response(
  p_participant_id uuid,
  p_user_id uuid,
  p_itinerary_id uuid,
  p_recommendation_ratings jsonb,
  p_itinerary_quality_ratings jsonb,
  p_customization_ratings jsonb,
  p_system_value_ratings jsonb,
  p_difficulties text,
  p_improvement_priority text,
  p_feature_suggestions text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  completed_count bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM survey.participants p
    WHERE p.id = p_participant_id AND p.user_id = p_user_id
  ) THEN
    RAISE EXCEPTION 'Survey participant not found';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM travel.itineraries i
    WHERE i.id = p_itinerary_id AND i.creator_id = p_user_id
  ) THEN
    RAISE EXCEPTION 'Itinerary does not belong to participant';
  END IF;

  INSERT INTO survey.responses (
    participant_id,
    user_id,
    itinerary_id,
    recommendation_ratings,
    itinerary_quality_ratings,
    customization_ratings,
    system_value_ratings,
    difficulties,
    improvement_priority,
    feature_suggestions
  )
  VALUES (
    p_participant_id,
    p_user_id,
    p_itinerary_id,
    p_recommendation_ratings,
    p_itinerary_quality_ratings,
    p_customization_ratings,
    p_system_value_ratings,
    trim(p_difficulties),
    trim(p_improvement_priority),
    trim(p_feature_suggestions)
  )
  ON CONFLICT (participant_id) DO UPDATE SET
    itinerary_id = EXCLUDED.itinerary_id,
    recommendation_ratings = EXCLUDED.recommendation_ratings,
    itinerary_quality_ratings = EXCLUDED.itinerary_quality_ratings,
    customization_ratings = EXCLUDED.customization_ratings,
    system_value_ratings = EXCLUDED.system_value_ratings,
    difficulties = EXCLUDED.difficulties,
    improvement_priority = EXCLUDED.improvement_priority,
    feature_suggestions = EXCLUDED.feature_suggestions,
    submitted_at = now(),
    updated_at = now();

  UPDATE survey.participants
  SET
    status = 'COMPLETED',
    current_itinerary_id = p_itinerary_id,
    completed_at = now(),
    last_seen_at = now(),
    updated_at = now()
  WHERE id = p_participant_id;

  INSERT INTO survey.events (
    participant_id, user_id, itinerary_id, event_type
  )
  VALUES (
    p_participant_id, p_user_id, p_itinerary_id, 'SURVEY_SUBMITTED'
  )
  ON CONFLICT (participant_id, event_key) DO NOTHING;

  SELECT COUNT(*) INTO completed_count FROM survey.responses;
  RETURN completed_count;
END;
$$;

REVOKE ALL ON FUNCTION public.survey_get_participant_by_email(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.survey_upsert_participant(uuid, text, text, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.survey_record_event(uuid, uuid, uuid, text, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.survey_submit_response(uuid, uuid, uuid, jsonb, jsonb, jsonb, jsonb, text, text, text) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.survey_get_participant_by_email(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.survey_upsert_participant(uuid, text, text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.survey_record_event(uuid, uuid, uuid, text, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.survey_submit_response(uuid, uuid, uuid, jsonb, jsonb, jsonb, jsonb, text, text, text) TO service_role;
